// IELTS Level 2 文章問題（Band 5.5-6.0 相当）
window.SENTENCES_L2 = [
  { id:4, level:2, sentence:"Overfishing has severely _____ fish stocks in the Pacific Ocean.", answer:"depleted", translation:"乱獲によって太平洋の魚類資源が深刻に枯渇している。", explanation:"deplete = 資源を使い果たす、大幅に減らす", choices:["depleted","generated","enhanced","maintained","obtained","modified"] },
  { id:5, level:2, sentence:"Air pollution in industrial cities has _____ significantly over the last decade.", answer:"deteriorated", translation:"工業都市の大気汚染はここ10年で著しく悪化している。", explanation:"deteriorate = 状況・環境が悪化する", choices:["deteriorated","fluctuated","emerged","attained","collaborated","allocated"] },
  { id:10, level:2, sentence:"Planting trees along river banks can help _____ the risk of flooding.", answer:"mitigate", translation:"川岸に木を植えることは洪水のリスクを緩和するのに役立つ。", explanation:"mitigate = 悪影響やリスクを軽減・緩和する", choices:["mitigate","exacerbate","ignore","monitor","determine","cite"] },
  { id:11, level:2, sentence:"The new policy aims to _____ the use of single-use plastics in all supermarkets.", answer:"prohibit", translation:"新しい政策は全スーパーマーケットにおける使い捨てプラスチックの使用を禁止することを目的としている。", explanation:"prohibit = 法律・規則で正式に禁止する", choices:["prohibit","promote","maintain","generate","establish","integrate"] },
  { id:15, level:2, sentence:"Many scientists _____ for a complete ban on the use of fossil fuels by 2050.", answer:"advocate", translation:"多くの科学者が2050年までの化石燃料の完全廃止を主張している。", explanation:"advocate for ～ = ～を支持・擁護する", choices:["advocate","neglect","assume","obtain","pursue","concentrate"] },
  { id:16, level:2, sentence:"The government needs to _____ more resources to public health in rural areas.", answer:"allocate", translation:"政府は農村部の公衆衛生にさらに多くの資源を割り当てる必要がある。", explanation:"allocate = 目的に応じて資金・資源を配分する", choices:["allocate","restrict","retain","monitor","generate","reveal"] },
  { id:17, level:2, sentence:"Economists _____ that unemployment rates will rise during the economic recession.", answer:"anticipate", translation:"エコノミストは景気後退中に失業率が上昇すると予測している。", explanation:"anticipate = 将来の出来事を予測して準備する", choices:["anticipate","ignore","manipulate","cite","distribute","facilitate"] },
  { id:19, level:2, sentence:"Industrial pollutants have severely _____ the quality of water in many river systems.", answer:"deteriorated", translation:"工業汚染物質は多くの河川システムの水質を著しく悪化させた。", explanation:"deteriorate = 悪化する（または悪化させる）", choices:["deteriorated","generated","maintained","stimulated","established","mitigated"] },
  { id:20, level:2, sentence:"The two countries agreed to _____ on research into sustainable agricultural practices.", answer:"collaborate", translation:"両国は持続可能な農業慣行の研究で協力することに合意した。", explanation:"collaborate on ～ = ～について共同研究・協力する", choices:["collaborate","allocate","anticipate","restrict","perceive","regulate"] },
  { id:26, level:2, sentence:"The pollution levels in the river _____ dramatically during the rainy season.", answer:"fluctuate", translation:"川の汚染レベルは雨季に大幅に変動する。", explanation:"fluctuate = 不規則に変動する、上下する", choices:["fluctuate","decline","emerge","deteriorate","generate","maintain"] },
  { id:30, level:2, sentence:"New technologies have _____ communication across vast geographical distances.", answer:"facilitated", translation:"新技術は広大な地理的距離を越えたコミュニケーションを促進した。", explanation:"facilitate = プロセスを容易にする、促進する", choices:["facilitated","restricted","neglected","ceased","modified","maintained"] },
  { id:33, level:2, sentence:"The report warns that over-reliance on fossil fuels will _____ natural resources.", answer:"deplete", translation:"その報告書は化石燃料への過度な依存が天然資源を枯渇させると警告している。", explanation:"deplete = 資源を使い果たす", choices:["deplete","enhance","generate","maintain","stimulate","establish"] },
  { id:34, level:2, sentence:"Recycling programmes help to _____ the amount of waste sent to landfill.", answer:"minimize", translation:"リサイクルプログラムは埋め立て地に送られる廃棄物の量を最小化するのに役立つ。", explanation:"minimize = できるだけ小さくする、最小化する", choices:["minimize","maximize","monitor","regulate","restrict","distribute"] },
  { id:35, level:2, sentence:"The use of renewable energy is _____ throughout Scandinavian countries.", answer:"prevalent", translation:"再生可能エネルギーの使用は北欧諸国全体で広く普及している。", explanation:"prevalent = 広く普及している、一般的な", choices:["prevalent","sufficient","gradual","considerable","relevant","transparent"] },
  { id:36, level:2, sentence:"Tax incentives have been introduced to _____ investment in green technology.", answer:"stimulate", translation:"グリーンテクノロジーへの投資を刺激するために税制上のインセンティブが導入された。", explanation:"stimulate = 活性化する、促進する", choices:["stimulate","restrict","neglect","monitor","obtain","determine"] },
  { id:38, level:2, sentence:"The study's findings have important _____ for public health policy.", answer:"implications", translation:"その研究の発見は公衆衛生政策にとって重要な示唆がある。", explanation:"implications = 影響、示唆（implicate/implyの名詞形）", choices:["implications","perspectives","phenomena","circumstances","tendencies","proportions"] },
  { id:42, level:2, sentence:"The project aims to _____ solar energy technology into existing power grids.", answer:"integrate", translation:"そのプロジェクトは太陽エネルギー技術を既存の電力グリッドに統合することを目的としている。", explanation:"integrate A into B = AをBに統合する", choices:["integrate","generate","distribute","implement","facilitate","establish"] },
  { id:43, level:2, sentence:"It is _____ that climate change will affect crop yields in many regions.", answer:"inevitable", translation:"気候変動が多くの地域の作物収穫量に影響を与えることは避けられない。", explanation:"inevitable = 避けられない、必然的な", choices:["inevitable","controversial","ambiguous","gradual","sufficient","relevant"] },
  { id:47, level:2, sentence:"Strong _____ such as roads, bridges and water systems are essential for economic development.", answer:"infrastructure", translation:"道路、橋、水道システムなどの強固なインフラは経済発展に不可欠だ。", explanation:"infrastructure = 社会の基盤となる施設・システム", choices:["infrastructure","phenomenon","perspective","tendency","proportion","circumstance"] },
  { id:48, level:2, sentence:"Social media has been shown to _____ negative body image among young people.", answer:"reinforce", translation:"ソーシャルメディアは若者の間でネガティブなボディイメージを強化することが示されている。", explanation:"reinforce = 強化する、補強する", choices:["reinforce","reduce","neglect","reveal","modify","justify"] }
];
